---
name: gh-cli

instance_groups:
- name: gh-cli
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: gh-cli
    release: gh-cli
    properties:
      installation_only: true

variables: []

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: gh-cli
  version: latest
