---
name: gh-cli

instance_groups:
- name: gh-cli
  azs: [z1]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: gh-cli
    release: gh-cli
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: gh-cli
  sha1: 6578d34f87d870c95d956dd0313b2b525df5d1db
  url: https://github.com/starkandwayne/gh-boshrelease/releases/download/v0.3.1/gh-cli-0.3.1.tgz
  version: 0.3.1
