<% if properties.installation_only == false -%>
<% if_p("hosts_file") do |config| -%>
<%= config %>
<% end.else do -%>
<%= p("hostname") %>:
  oauth_token: <%= p("token") %>
  user: <%= p("username") %>
  git_protocol: <%= p("protocol") %>
<% end -%>
<% end -%>